name: Go package

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.x'

      - name: Init TestRepo git sub repo
        run: ./bin/init_test_repo.sh

      - name: Check if repo was created
        run: |
          if [ ! -d "TestRepo" ]; then
            echo "TestRepo directory does not exist."
            exit 1
          fi

      - name: Build Step
        run: go build -v ./...

      - name: Install Dependencies
        run: go get .

      - name: Run Tests
        run: go test -v ./...
